import { useState } from "react";
import { SafeAreaView, ScrollView, Text, View, Card, CardContent, Pressable, Badge, Button, Sheet, SheetTrigger, SheetContent } from "@/components/ui";
import { Copy, Check, Hash, Mic, Video, Image as ImageIcon, Film, Play, Download, Share2, FileText, Sparkles, Heart } from "lucide-react-native";
import { useQuery, useMutation } from "convex/react";
import { api } from "@/convex/_generated/api";
import * as Clipboard from "expo-clipboard";
import { Platform } from "react-native";

const platforms = [
  { id: "tiktok", label: "TikTok", duration: "15-60 sec" },
  { id: "youtube", label: "YouTube Shorts", duration: "30-60 sec" },
  { id: "instagram", label: "Instagram Reels", duration: "Engaging" },
  { id: "linkedin", label: "LinkedIn", duration: "Professional" },
  { id: "x", label: "X (Twitter)", duration: "Thread" },
];

export default function ScriptsScreen() {
  const [activePlatform, setActivePlatform] = useState("tiktok");
  const [copiedField, setCopiedField] = useState<string | null>(null);
  const [showExportSheet, setShowExportSheet] = useState(false);
  
  const scripts = useQuery(api.scripts.getScripts) ?? [];
  const favorites = useQuery(api.favorites.getFavorites, {}) ?? [];
  const addFavorite = useMutation(api.favorites.addFavorite);
  const removeFavorite = useMutation(api.favorites.removeFavoriteByItemId);

  const copyToClipboard = async (field: string, text: string) => {
    await Clipboard.setStringAsync(text);
    setCopiedField(field);
    setTimeout(() => setCopiedField(null), 2000);
  };

  const copyAllContent = async (script: any, platform: string) => {
    const platformVersion = script.platformVersions?.[platform];
    const fullContent = `🎬 ${script.title}

🪝 HOOK:
"${platformVersion?.adaptedHook || script.hook}"

📝 SCRIPT:
${platformVersion?.adaptedScript || script.script}

📱 CAPTION:
${script.caption}

🎯 CTA:
${script.cta}

#️⃣ HASHTAGS:
${script.hashtags}

---
Generated by AI Content OS
`;
    await Clipboard.setStringAsync(fullContent);
    setCopiedField("all");
    setTimeout(() => setCopiedField(null), 2000);
  };

  const exportAsMarkdown = (script: any, platform: string) => {
    const platformVersion = script.platformVersions?.[platform];
    const markdown = `# ${script.title}

## Platform: ${platforms.find(p => p.id === platform)?.label}

### 🪝 Hook
> "${platformVersion?.adaptedHook || script.hook}"

### 📝 Script
${platformVersion?.adaptedScript || script.script}

### 📱 Caption
${script.caption}

### 🎯 Call-to-Action
${script.cta}

### #️⃣ Hashtags
${script.hashtags}

---

## 🎨 AI Production Assets

### Video Prompt
${script.videoPrompt}

### Image Prompt
${script.imagePrompt}

### Voiceover
${script.voiceover}

### B-Roll Suggestions
${script.broll?.map((item: string, i: number) => `${i + 1}. ${item}`).join('\n')}

### Thumbnail Text
${script.thumbnail}

---
*Generated by AI Content Operating System*
`;
    return markdown;
  };

  const handleExport = async (format: 'clipboard' | 'markdown') => {
    if (scripts.length === 0) return;
    
    const script = scripts[0];
    
    if (format === 'clipboard') {
      await copyAllContent(script, activePlatform);
    } else if (format === 'markdown') {
      const markdown = exportAsMarkdown(script, activePlatform);
      await Clipboard.setStringAsync(markdown);
      setCopiedField("markdown");
      setTimeout(() => setCopiedField(null), 2000);
    }
    
    setShowExportSheet(false);
  };

  const isFavorited = (scriptId: string) => {
    return favorites.some(f => f.itemId === scriptId);
  };

  const toggleFavorite = async (script: any) => {
    if (isFavorited(script._id)) {
      await removeFavorite({ itemId: script._id });
    } else {
      await addFavorite({
        itemType: "script",
        itemId: script._id,
        title: script.title,
      });
    }
  };

  if (scripts.length === 0) {
    return (
      <SafeAreaView edges={["top"]} className="flex-1 bg-background">
        <ScrollView className="flex-1" contentContainerClassName="p-6">
          <View className="mb-6">
            <Text variant="muted" className="mb-1">Step 3, 4 & 5</Text>
            <Text variant="h1" className="text-3xl">Scripts & Assets</Text>
            <Text variant="muted" className="mt-2">
              AI-generated hooks, scripts, captions, and production assets.
            </Text>
          </View>
          
          <Card className="bg-muted/50">
            <CardContent className="p-5">
              <Text className="text-center text-muted-foreground">
                No scripts yet. Go to the Ideas tab and tap "Generate Script" on any idea to create your first content script.
              </Text>
            </CardContent>
          </Card>
        </ScrollView>
      </SafeAreaView>
    );
  }

  const activeScript = scripts[0];
  const platformVersion = activeScript.platformVersions?.[activePlatform];

  return (
    <SafeAreaView edges={["top"]} className="flex-1 bg-background">
      <ScrollView className="flex-1" contentContainerClassName="p-6 pb-24">
        {/* Header */}
        <View className="mb-6">
          <Text variant="muted" className="mb-1">Step 3, 4 & 5</Text>
          <Text variant="h1" className="text-3xl">Scripts & Assets</Text>
          <Text variant="muted" className="mt-2">
            Hooks, scripts, captions, and platform-specific versions.
          </Text>
        </View>

        {/* Script Selector with Favorite */}
        <View className="flex-row items-center justify-between mb-4">
          <Text className="font-semibold">Active Script</Text>
          {scripts.length > 0 && (
            <Pressable onPress={() => toggleFavorite(scripts[0])}>
              <Heart 
                size={24} 
                className={isFavorited(scripts[0]._id) ? "text-red-500 fill-red-500" : "text-muted-foreground"} 
              />
            </Pressable>
          )}
        </View>

        <ScrollView horizontal showsHorizontalScrollIndicator={false} className="mb-6">
          <View className="flex-row gap-3">
            {scripts.map((script, index) => (
              <Pressable
                key={script._id}
                onPress={() => {}}
                className={`p-3 rounded-xl min-w-[200px] ${
                  index === 0 ? "bg-primary" : "bg-muted"
                }`}
              >
                <Text 
                  className={`font-semibold ${
                    index === 0 ? "text-primary-foreground" : "text-muted-foreground"
                  }`}
                  numberOfLines={2}
                >
                  {script.title}
                </Text>
                <Text 
                  className={`text-xs mt-1 ${
                    index === 0 ? "text-primary-foreground/70" : "text-muted-foreground/70"
                  }`}
                >
                  {new Date(script.createdAt).toLocaleDateString()}
                </Text>
              </Pressable>
            ))}
          </View>
        </ScrollView>

        {/* Platform Selector */}
        <Text className="font-semibold mb-3">Platform Version</Text>
        <ScrollView horizontal showsHorizontalScrollIndicator={false} className="mb-6">
          <View className="flex-row gap-2">
            {platforms.map((platform) => (
              <Pressable
                key={platform.id}
                onPress={() => setActivePlatform(platform.id)}
                className={`px-4 py-3 rounded-xl ${
                  activePlatform === platform.id ? "bg-primary" : "bg-muted"
                }`}
              >
                <Text 
                  className={`font-semibold ${
                    activePlatform === platform.id ? "text-primary-foreground" : "text-muted-foreground"
                  }`}
                >
                  {platform.label}
                </Text>
                <Text 
                  className={`text-xs ${
                    activePlatform === platform.id ? "text-primary-foreground/70" : "text-muted-foreground/70"
                  }`}
                >
                  {platform.duration}
                </Text>
              </Pressable>
            ))}
          </View>
        </ScrollView>

        {/* Export Actions */}
        <View className="flex-row gap-3 mb-6">
          <Pressable 
            onPress={() => handleExport('clipboard')}
            className="flex-1 bg-primary p-4 rounded-xl flex-row items-center justify-center"
          >
            {copiedField === "all" ? (
              <Check size={20} className="text-primary-foreground mr-2" />
            ) : (
              <Copy size={20} className="text-primary-foreground mr-2" />
            )}
            <Text className="text-primary-foreground font-semibold">
              {copiedField === "all" ? "Copied!" : "Copy All"}
            </Text>
          </Pressable>
          
          <Pressable 
            onPress={() => setShowExportSheet(true)}
            className="flex-1 bg-muted p-4 rounded-xl flex-row items-center justify-center"
          >
            <Download size={20} className="text-foreground mr-2" />
            <Text className="text-foreground font-semibold">Export</Text>
          </Pressable>
        </View>

        {/* Hook */}
        <View className="mb-4">
          <View className="flex-row items-center justify-between mb-2">
            <View className="flex-row items-center">
              <Play size={18} className="text-red-500 mr-2" />
              <Text className="font-semibold">Hook (First 3 Seconds)</Text>
            </View>
            <Pressable onPress={() => copyToClipboard("hook", platformVersion?.adaptedHook || activeScript.hook)}>
              {copiedField === "hook" ? (
                <Check size={18} className="text-green-500" />
              ) : (
                <Copy size={18} className="text-muted-foreground" />
              )}
            </Pressable>
          </View>
          <Card>
            <CardContent className="p-4">
              <Text className="text-lg font-medium leading-relaxed">
                "{platformVersion?.adaptedHook || activeScript.hook}"
              </Text>
            </CardContent>
          </Card>
        </View>

        {/* Script */}
        <View className="mb-4">
          <View className="flex-row items-center justify-between mb-2">
            <View className="flex-row items-center">
              <Mic size={18} className="text-blue-500 mr-2" />
              <Text className="font-semibold">Script</Text>
            </View>
            <Pressable onPress={() => copyToClipboard("script", platformVersion?.adaptedScript || activeScript.script)}>
              {copiedField === "script" ? (
                <Check size={18} className="text-green-500" />
              ) : (
                <Copy size={18} className="text-muted-foreground" />
              )}
            </Pressable>
          </View>
          <Card>
            <CardContent className="p-4">
              <Text className="leading-relaxed">{platformVersion?.adaptedScript || activeScript.script}</Text>
            </CardContent>
          </Card>
        </View>

        {/* Caption */}
        <View className="mb-4">
          <View className="flex-row items-center justify-between mb-2">
            <View className="flex-row items-center">
              <Hash size={18} className="text-purple-500 mr-2" />
              <Text className="font-semibold">Caption</Text>
            </View>
            <Pressable onPress={() => copyToClipboard("caption", activeScript.caption)}>
              {copiedField === "caption" ? (
                <Check size={18} className="text-green-500" />
              ) : (
                <Copy size={18} className="text-muted-foreground" />
              )}
            </Pressable>
          </View>
          <Card>
            <CardContent className="p-4">
              <Text className="leading-relaxed whitespace-pre-line">{activeScript.caption}</Text>
            </CardContent>
          </Card>
        </View>

        {/* CTA */}
        <View className="mb-4">
          <View className="flex-row items-center justify-between mb-2">
            <Text className="font-semibold">Call-to-Action</Text>
            <Pressable onPress={() => copyToClipboard("cta", activeScript.cta)}>
              {copiedField === "cta" ? (
                <Check size={18} className="text-green-500" />
              ) : (
                <Copy size={18} className="text-muted-foreground" />
              )}
            </Pressable>
          </View>
          <Card className="bg-primary/5">
            <CardContent className="p-4">
              <Text>{activeScript.cta}</Text>
            </CardContent>
          </Card>
        </View>

        {/* Hashtags */}
        <View className="mb-6">
          <View className="flex-row items-center justify-between mb-2">
            <Text className="font-semibold">Hashtags</Text>
            <Pressable onPress={() => copyToClipboard("hashtags", activeScript.hashtags)}>
              {copiedField === "hashtags" ? (
                <Check size={18} className="text-green-500" />
              ) : (
                <Copy size={18} className="text-muted-foreground" />
              )}
            </Pressable>
          </View>
          <View className="flex-row flex-wrap gap-2">
            {activeScript.hashtags.split(" ").map((tag, index) => (
              <Badge key={index} variant="secondary">
                <Text className="text-xs">{tag}</Text>
              </Badge>
            ))}
          </View>
        </View>

        {/* AI Production Assets - Step 5 */}
        <Text variant="h3" className="mb-4">AI Production Assets</Text>
        
        {/* Video Prompt */}
        <Card className="mb-4">
          <CardContent className="p-4">
            <View className="flex-row items-center justify-between mb-3">
              <View className="flex-row items-center">
                <Video size={18} className="text-pink-500 mr-2" />
                <Text className="font-semibold">Video Generation Prompt</Text>
              </View>
              <Pressable onPress={() => copyToClipboard("video", activeScript.videoPrompt || "")}>
                {copiedField === "video" ? (
                  <Check size={16} className="text-green-500" />
                ) : (
                  <Copy size={16} className="text-muted-foreground" />
                )}
              </Pressable>
            </View>
            <Text variant="muted" className="text-sm leading-relaxed">{activeScript.videoPrompt}</Text>
          </CardContent>
        </Card>

        {/* Image Prompt */}
        <Card className="mb-4">
          <CardContent className="p-4">
            <View className="flex-row items-center justify-between mb-3">
              <View className="flex-row items-center">
                <ImageIcon size={18} className="text-indigo-500 mr-2" />
                <Text className="font-semibold">Image Generation Prompt</Text>
              </View>
              <Pressable onPress={() => copyToClipboard("image", activeScript.imagePrompt || "")}>
                {copiedField === "image" ? (
                  <Check size={16} className="text-green-500" />
                ) : (
                  <Copy size={16} className="text-muted-foreground" />
                )}
              </Pressable>
            </View>
            <Text variant="muted" className="text-sm leading-relaxed">{activeScript.imagePrompt}</Text>
          </CardContent>
        </Card>

        {/* Voiceover */}
        <Card className="mb-4">
          <CardContent className="p-4">
            <View className="flex-row items-center justify-between mb-3">
              <View className="flex-row items-center">
                <Mic size={18} className="text-orange-500 mr-2" />
                <Text className="font-semibold">Voiceover Script</Text>
              </View>
              <Pressable onPress={() => copyToClipboard("voiceover", activeScript.voiceover || "")}>
                {copiedField === "voiceover" ? (
                  <Check size={16} className="text-green-500" />
                ) : (
                  <Copy size={16} className="text-muted-foreground" />
                )}
              </Pressable>
            </View>
            <Text variant="muted" className="text-sm leading-relaxed">{activeScript.voiceover}</Text>
          </CardContent>
        </Card>

        {/* B-Roll */}
        <Card className="mb-4">
          <CardContent className="p-4">
            <View className="flex-row items-center mb-3">
              <Film size={18} className="text-teal-500 mr-2" />
              <Text className="font-semibold">B-Roll Suggestions</Text>
            </View>
            <View className="gap-2">
              {activeScript.broll?.map((item, index) => (
                <View key={index} className="flex-row items-center">
                  <Text className="text-muted-foreground mr-2">{index + 1}.</Text>
                  <Text variant="muted" className="text-sm flex-1">{item}</Text>
                </View>
              ))}
            </View>
          </CardContent>
        </Card>

        {/* Thumbnail */}
        <Card className="mb-6">
          <CardContent className="p-4">
            <View className="flex-row items-center justify-between mb-3">
              <View className="flex-row items-center">
                <Sparkles size={18} className="text-yellow-500 mr-2" />
                <Text className="font-semibold">Thumbnail Text</Text>
              </View>
              <Pressable onPress={() => copyToClipboard("thumbnail", activeScript.thumbnail || "")}>
                {copiedField === "thumbnail" ? (
                  <Check size={16} className="text-green-500" />
                ) : (
                  <Copy size={16} className="text-muted-foreground" />
                )}
              </Pressable>
            </View>
            <View className="bg-black p-4 rounded-lg">
              <Text className="text-white text-xl font-bold text-center">{activeScript.thumbnail}</Text>
            </View>
          </CardContent>
        </Card>
      </ScrollView>

      {/* Export Sheet */}
      {showExportSheet && (
        <View className="absolute inset-0 bg-black/50 justify-end">
          <View className="bg-background rounded-t-3xl p-6">
            <View className="flex-row items-center justify-between mb-6">
              <Text variant="h3">Export Script</Text>
              <Pressable onPress={() => setShowExportSheet(false)}>
                <Text className="text-muted-foreground">Close</Text>
              </Pressable>
            </View>
            
            <View className="gap-3">
              <Pressable 
                onPress={() => handleExport('clipboard')}
                className="flex-row items-center p-4 bg-muted rounded-xl"
              >
                <FileText size={24} className="text-primary mr-4" />
                <View className="flex-1">
                  <Text className="font-semibold">Copy as Text</Text>
                  <Text variant="muted" className="text-xs">Copy formatted script to clipboard</Text>
                </View>
                {copiedField === "all" && <Check size={20} className="text-green-500" />}
              </Pressable>
              
              <Pressable 
                onPress={() => handleExport('markdown')}
                className="flex-row items-center p-4 bg-muted rounded-xl"
              >
                <Download size={24} className="text-primary mr-4" />
                <View className="flex-1">
                  <Text className="font-semibold">Copy as Markdown</Text>
                  <Text variant="muted" className="text-xs">Full script with all assets</Text>
                </View>
                {copiedField === "markdown" && <Check size={20} className="text-green-500" />}
              </Pressable>
            </View>
          </View>
        </View>
      )}
    </SafeAreaView>
  );
}
